<?php

/**
 * AclRecoveryPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AclRecoveryPasswordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AclRecoveryPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AclRecoveryPassword');
    }
}