<?php

/**
 * AclResourcesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AclResourcesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AclResourcesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AclResources');
    }
}