<?php

/**
 * AclRoleHasResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AclRoleHasResourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AclRoleHasResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AclRoleHasResource');
    }
}