<?php

/**
 * AclRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AclRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AclRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AclRoles');
    }
}