<?php

/**
 * AclUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AclUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AclUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AclUsers');
    }
}