<?php

/**
 * BudgetQuestionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetQuestionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetQuestionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetQuestions');
    }
}