<?php

/**
 * BudgetPosibleAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetPosibleAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetPosibleAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetPosibleAnswers');
    }
}