<?php

/**
 * BudgetsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Budgets');
    }
}