<?php

/**
 * CategoryHasServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryHasServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryHasServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryHasService');
    }
}