<?php

/**
 * CategoryHasSeviceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryHasSeviceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryHasSeviceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryHasSevice');
    }
}