<?php

/**
 * PruebasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PruebasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PruebasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pruebas');
    }
}