<?php

/**
 * ServiceInPackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceInPackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceInPackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceInPack');
    }
}