<?php

/**
 * ServiceCategoryHasServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceCategoryHasServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceCategoryHasServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceCategoryHasService');
    }
}