<?php

/**
 * ServiceLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceLine');
    }
}