<?php

/**
 * ServicePackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicePackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicePackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicePack');
    }
}