<?php

/**
 * SitesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SitesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sites');
    }
}